### ISSUE TITLE
404 Page is broken if missing non-html content

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#101]
I ran a zimit of [survivor library](http://www.survivorlibrary.com/index.php/8-category/43-library-engineering-electrical) ([task here](https://farm.youzim.it/pipeline/1e3882e7a0fe71d29367b016)) - the webpage is a collection of PDF files and has no other fancy content. 
![Capture d’écran 2021-08-10 à 09 36 05](https://user-images.githubusercontent.com/21675885/128827275-d00d2af8-c108-4e81-ae87-74ca222bd9d0.png)

I ended up with a healthy 11.6 Gb file, yet I am unable to open any of the PDF (as in: nothing happens - I don't even get an error message)

**Comment by rgaudin** [comment]
Thanks for the report. Couple additions:

- Many many PDF files do work
- More doesn't
- Not working means being redirected to a blank page.

What happens is that the PDF is missing (404) and what's being shown is the *404 Error template* that we bundle. Unfortunately, the JS piece that displays the Error message breaks because it can't find the `#error` selector to put it in. That's a bug we can fix.

@Popolechien, given links in the first categories work fine, it's possible you just hit the limit and the missing ones are just excluded. Actually debug tab shows it did hit the limit. I suggest you create a recipe for this on zimfarm if it matches zimfarm's requirements.


<img width="1039" alt="Screen Shot 2021-08-10 at 12 18 54" src="https://user-images.githubusercontent.com/57929/128866020-70934f15-aeeb-4f19-b6ff-99999ed537ca.png">

**Comment by Popolechien** [comment]
@rgaudin Did you try it on Kiwix-serve? Because I'm on Android and really tried a lot of files, to no avail (in which case then we have a second issue).

**Comment by rgaudin** [comment]
Yes I tried on kiwix-serve. Test the ones in Engineering

**Comment by Popolechien** [comment]
Yup - tried Engineering- Electrical, General, Hydraulics: nothing happens. Should I open a ticket on /kiwix/android?

**Comment by rgaudin** [comment]
Yes, First book in first category (Accounting) works on kiwix-serve

**Comment by rgaudin** [comment]
Issue's too old now ; ZIM is gone and scraper has changed a lot. I advise you retry if you're still interested and open a new ticket.
