### ISSUE TITLE
Approximate time to generate .zim on zimit?

### ISSUE THREAD

**Issue by samuk** [openzim/zimit#113]
I requested 3x Zim files on the 23rd & 24th of Feb. Is the queue long at the moment? Or would you have expected these to generate by now?

**Comment by rgaudin** [comment]
Hi, the queue is very long. ATM we have 188 tasks awaiting a slot. This is mostly due to us shutting down the worker for a couple weeks due to a technical issue.
Other reason is we let any request in while some are clearly inefficient for various reasons:
- Wikipedia requests: we have dedicated, ready, and high quality Wikipedia ZIMs for most languages
- download.kiwix.org requests: will create a ZIM offering a lot of ZIM files for download…
- library.kiwix.org… what's served there is already available as ZIM files
- Youtube. Very unlikely this will be useful at all while we have a per-user/channel/playlists scraper for this

All of those create very-very long tasks that end up not being much useful. We plan to offer alternative to users requesting those but this ticket has not been implemented yet.

Thanks for bringing that up, we need to think about how we want to tackle this recurrent issue (not the current bottleneck)
