### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#135]
- [x] Secure we're using a released warc2zim
- [x] Secure the CI is green on git `master`
- [x] Update the Changelog
- [x] Close current milestone and create new one incrementaly (_a priori_ a minor version)
- [x] Create a tag on git
- [x] Secure new version is published on https://hub.docker.com/r/openzim/zimit
- [x] Update the Github release with the Changelog
- [ ] Create new empty entry in Changelog (placeholder for future entries)
- [ ] Advertise this new version

**Comment by Jaifroid** [comment]
@rgaudin Thank you very much for this update. I am not 100% sure if this code is now published and is being used, but I noticed that at least some new Zimit archives being released now seem to be using a hybrid of C/ and A/ namespaces, i.e. there is an A/ namespace inside the C/ namespace, and the ZIM archives are of minorVersion 1.

I can adapt my code to handle this, but I wondered if this hybrid is intended to be a stable format going forward (for Zimit archives). And curious as to why you didn't choose to swap the A/ namescpace for the C/ namespace rather than putting A/ inside C/. I already had code to handle an anticipated switch to C/ (i.e. my code is agnostic as to the content namespace), but I didn't anticipate a switch to C/A/ !

![image](https://user-images.githubusercontent.com/4304337/177931211-9d23ddf1-7c0b-4495-85aa-1fcf4c185a07.png)

![image](https://user-images.githubusercontent.com/4304337/177932100-2d6c6f87-78ac-4fb9-8a62-b1216521eb25.png)

**Comment by rgaudin** [comment]
@Jaifroid this ticket is a checklist for what's to be done when releasing. Current zimit is 1.2 and zimfarm is currently using it or master. Both versions apply to your comment.

With the move to libzim7, there are no such things as namespaces from a ZIM creator's perspective. The *removal of namespaces* means putting everything under that new `C` namespace except for internals.
You know we used to store warc content under `A` and warc headers under `H`. We're continuing to do this except those are now prefix under `C`.

One way to improve this is to get rid of the `A/` prefix for content and keep the headers as it it.

With upcoming support for custom indexation, we may rethink warc2zim a bit but that thinking hasn't started yet.

**Comment by Jaifroid** [comment]
OK, thanks. Nevertheless, we've ended up with a ZIM type that is really weird for anyone trying to develop to the OpenZIM specification (because it is a hybrid of the old spec and the new). Technically, the format still has [Namespaces](https://wiki.openzim.org/wiki/ZIM_file_format#Namespaces) (C, M, W, X and also H), and our backend is *very* aware of these namespaces and has to account for them. Please understand this isn't a criticism, I understand how we got here. My question really is whether I need to develop to this hybrid format, as it means putting code in the backend specifically to account for an A/ namespace inside the Content namesapce.

IMHO it would be much better if the new warc2zim + zimit could simply swap the A/ and the C/ namespaces. It would be completely logical, because the old A/ namespace for warc2zim ZIM types was effectively doing what the C/ namespace is supposed to be doing for OpenZIM Type 1 ZIMs -- i.e., everything, images, JS, all user content goes under a single all-inclusive namespace.

**Comment by rgaudin** [comment]
I think you read it wrong. Those `A/` and `H/` **are not namespaces** but prefixes, all within the `C` namespace. We won't move the `H/`-prefixed entries into `H` namespace because we don't have access to it anymore. The new libzim7 **usage/convention** is that ZIM creators don't use namespaces. All entries go into `C` and metadata are placed (by libzim) into `M`. The other namespaces are used (or not) by libzim for internal purposes (indexes, etc).

I understand how this affects your code as you'll have to handle differently previous warc2zim-ZIMs with entries in `A` and `H` and new ones in `C` at different prefixes. Sorry I did not anticipate this being an issue.

Let me know how you'd prefer it to evolve, within the new convention… or take this conversation up to @mgautierfr and @kelson42.

**Comment by Jaifroid** [comment]
That's an important clarification, thank you. Indeed, I had not quite understood the difference there, and that A/ and H/ are now prefixes within the Content namespace. I think I'll just have to support this in the code. It shouldn't be too tricky. It sometimes feels as if the ZIM Farm is turning into a ZIM  Zoo of exotic ZIM formats!!! 😉

**Comment by kelson42** [comment]
@Jaifroid This kind of ZIM is indeed a bit of wip. The bright side is that it push us to improve the ZIM format and our concepts. The dark side, is hard additonal work and kind of experimental/unstable approach.

**Comment by Jaifroid** [comment]
I'd be happy to move my posts above to a dedicated issue on warc2zim on the location of WARC assets in Type 1 ZIMs, if it would be useful to set some guidelines. But I defer to @rgaudin as to what the best way forward with this is.

**Comment by rgaudin** [comment]
Yes, a new ticket referencing this one on warc2zim would be good.
