### ISSUE TITLE
Is there a way to pause a crawl in docker?

### ISSUE THREAD

**Issue by ristein** [openzim/zimit#151]
I started downloading some webpages but one seems to be taking longer than expected.
It would be great if I could restart the server and continue scraping afterwards.
I tried docker stop and docker pause/unpause but both seemed to work if done on a container younger than few minutes as statsFile gets refreshed, but sometimes two instances seem to be running as the numbers after "done" are increasing in two different lines (like 24, 25, 26, 5, 27, 6, 28, 29, 7, 8, 30), other times the container is exited/crashed.

**Comment by rgaudin** [comment]
There are a few `saveState` options in browsertrix but we haven't exposed those in zimit, because I'm not sure how they work ; haven't tested and it's not really a use case for us.
If you want to experiment (by manually launching `crawler` in the container with the appropriate options and then `warc2zim`) and share more about how it actually works we'll be happy to expose those.

**Comment by ristein** [comment]
thanks, will stick to no reboot until done
