### ISSUE TITLE
Zimit only scrapes first page

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#153]
I've launched zimit on http://www.birdsofladakh.org/ and gotten a 1.64MB zim file as a result, which is far from the 2-300MB expected. File hasn't yet moved to dev.library but will update issue if there's anything notable.

**Comment by Popolechien** [comment]
I should add that the website has been moved from [Nomadic Changthan](https://library.kiwix.org/nomadic-changthang_en_all_2022-06), which we have had for a while with no issue, so either they upgraded to something too fancy for zimit or we ran into a regression between June and now.

**Comment by rgaudin** [comment]
Care to share the recipe ?

**Comment by Popolechien** [comment]
https://farm.openzim.org/recipes/birds-of-ladakh

**Comment by rgaudin** [comment]
Was a recipe _error_ due to the change in scope behavior: recipe was using http://www.birdsofladakh.org/ which redirects and serves content from https://www.birdsofladakh.org/ but the website starts with links to https://birdsofladakh.org/xxx (no `www.`. So it's on a different domain.

It would have been possible to get around that playing with Scope parameters but I chose the easy route and changed url to https://birdsofladakh.org/. Scraper's been running for 13mn now…

**Comment by Popolechien** [comment]
Scraping worked, thank you.

The issue described in #154 (needs clean cache) nevertheless remains, but that's a separate problem.

The other thing missing, however, are youtube videos (I believe this is pending of an upcoming warc2zim release)
