### ISSUE TITLE
External links should not be open in a new tab

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#181]
Going to https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2023-02/A/mesquartierschinois.wordpress.com/ and clicking on the link « deux solitudes » opens the link https://fr.wikipedia.org/wiki/Deux_solitudes in a new tab.

IMO it should open the link in the current tab.

A side problem is that if I come back to the zim and click on the following link, then it opens in the previuosly open tab, but without switching to it.

**Comment by rgaudin** [comment]
Original link:

```html
<a href="https://fr.wikipedia.org/wiki/Deux_solitudes" target="_blank">deux solitudes</a>
```

So it's properly rewritten by the replayer as `target="___wb_replay_top_frame"` as to open in a new tab.

Is this a feature request to disable all target _blank ?

As for your second comment, it does open it in the previously opened tab again **but** it is switching to that tab for me on Firefox

**Comment by benoit74** [comment]
Do we really want to modify the source website HTML? This surprises me a bit, because so far the strategy has been to do our best to not do it as much as possible. It is still even a strong argument for issues around video playing where we say that we do not want to modify the HTML to add our own player.

And subquestion, is this really a 2.0 issue?

**Comment by benoit74** [comment]
What do we want to do on this?

**Comment by kelson42** [comment]
> Do we really want to modify the source website HTML?

I don't think so. If rhis is the original target, then I suggest to vlose this issue as INVALID.
