### ISSUE TITLE
Opentextbooks broken file

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#208]
Hi, the file below has been successfully generated but the links of (Get the books) are not scrapped, therefore not working.
Is there anything we can do to fix the recipe or we shall delete the file from the library?

https://download.kiwix.org/zim/zimit/opentextbooks_en_all_2023-05.zim
https://farm.openzim.org/recipes/opentextbooks_en_all

**Comment by rgaudin** [comment]
- Please also link to library/dev-library. It's not always easy to find since the name might be different from filename.
- Recipe scrapes `https://open.bccampus.ca/browse-our-collection/find-open-textbooks/` and whatever's found underneath.
- Get book links point to `https://collection.bccampus.ca/textbooks/uuid/{some-id}`
- You need to change the recipe to allow scraper to follow those book links

**Comment by kelson42** [comment]
@Popolechien @RavanJAltaie Sorry to jump on this, hopefuly I'm not missing the point.

Reading this ticket is annoying to me. I have myself requested many times that the process of publishing is rigoursly documented (whatever how it looks like) and respected. It seems none of this has been done and I consider this as hightly problematic.

I have open a [dedicated ticket](https://github.com/openzim/cms/issues/97) and, please. I urge you to work with PRIO0 on it.

**Comment by benoit74** [comment]
Looks like this has been solved, at least this is not a dev issue, but a config one, at least for now. Happy to assist in config if needed, tag me in zim-request issue if needed (no need to open an issue here if this is just a help for config)
