### ISSUE TITLE
Warc2zim errors not properly propagated

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#21]
Using the docker image, a failure in warc2zim will not be propagated as you can see on [this zimfarm run](https://farm.openzim.org/pipeline/5f7f3928371c94af34518ad1/debug).

Actually, I'm pretty sure that an error in zimit code wouldn't be propagated either ; but maybe it should be fixed at both locations…

Taking this opportunity to request that we switch from an entrypoint without a CMD to a CMD (possibly without an entrypoint). I see no reason to use the entrypoint at the moment and it prevents doing stuff like `docker run openzim/zimit warc2zim --help`

**Comment by ikreymer** [comment]
Switching it to cmd will mean that it will require the cmd to always be specified, eg. `docker run openzim/zimit /app/run.sh --url ...` instead of just `docker run openzim/zimit --url ...`

Note that you can still run warc2zim by running `docker run -it --entrypoint warc2zim openzim/zimit --help`

But it can be changed if you'd prefer to do it that way..

**Comment by rgaudin** [comment]
Don't really want to argue over simplicity to type one or another command.
Yes, please change it to a `zimit` command on PATH so that it's consistent with our other scrapers.
