### ISSUE TITLE
Service workers not supported

### ISSUE THREAD

**Issue by tempo660** [openzim/zimit#218]
Hi. I received my ZIM file as requested. It appears to have been a success but for the fact every page redirects me to an error message informing me that the page cannot be displayed because "service workers are not supported here."
![service-workers-error.png](https://github.com/openzim/zimit/assets/117519973/cd25ce27-cb62-4d44-9f95-abf5aef85370)

**Comment by benoit74** [comment]
Hi @tempo660,
What is your zim reader ? 
Only kiwix-android and kiwix-serve are supporting zimit for now.
There is experimental support on [pwa.kiwix.org](https://pwa.kiwix.org) ... but it is experimental.

**Comment by Popolechien** [comment]
Looks like OP is using Kiwix-desktop. 

@tempo660 You can open Kiwix-server (see settings, top right) as a workaround.

**Comment by benoit74** [comment]
If the same error appears on Kiwix for Android, then I don't get what is going on.

Two questions to move forward:
- is it possible to provide more details about your ZIM, or even sharing it with us so that we can debug what is going on?
- is it possible this problem is linked with some privacy settings (the message says that you shouldn't use Firefox in Private mode)

**Comment by benoit74** [comment]
Closing this issue for now. Do not hesitate to re-open it if you have more information to share.

More details about how to open ZIM files created by zimit has been posted [here](https://www.reddit.com/r/Kiwix/comments/170bnk1/how_to_open_zimit_files_eg_created_on_youzimit/).
