### ISSUE TITLE
DiskUtilization parameter not used

### ISSUE THREAD

**Issue by alison985** [openzim/zimit#219]
Hi, Using the latest Dockerfile image 1.5.3 on Ubuntu LTS I keep having zim activities stopped because of: `{"timestamp":"2023-09-24T19:18:10.135Z","logLevel":"info","context":"general","message":"Disk utilization threshold reached 90% > 90%, stopping","details":{}}`

I started passing in `--diskUtilization 120` because I was having files finish early and say the 90% based log message. 

Passing in `--diskUtilization 120` to the docker container does get it sent to the craawl `Running browsertrix-crawler crawl: crawl --failOnFailedSeed --workers 6 --waitUntil load --depth -1 --timeout 90 --exclude (event|calendar) --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --diskUtilization 120 --url [redacted] --userAgentSuffix +Zimit  --cwd /output/.tmpl7o_8cof` but it doesn't keep the files from ending early.

I would like the crawl to finish after content is finished. Am I doing something wrong or is this a bug?

**Comment by benoit74** [comment]
Hi,

What I understand from your issue is that:
- you are running `zimit` to crawl a website
- the crawl finishes with a message saying that the disk utilization has reach the 90% threshold, so the website is not totally crawled
- you tried to add the `--diskUtilization 120` parameter to `zimit` and saw that it is passed properly to `browzertrix-crawler` but the crawl is still not finishing properly

Some questions:
- did I get your case correctly?
- what is the "Disk utilization threshold reached ..." message when you add the `--diskUtilization 120` parameter?
- why do you expect that the crawler might use 120% of the available disk capacity? From my perspective, once the disk is full, it is full, so you cannot go above 100%
- how are you running the Docker image, directly with Docker CLI or any other tool?
- could you allocate more disk space? is your disk really full at the end of the crawl?

**Comment by ikreymer** [comment]
120 is not a valid value for this option, so it defaults back to 90 (though perhaps we should add a message there/error out instead). To disable this option, set it to 0 instead

**Comment by alison985** [comment]
@benoit74 Yes, that's my issue. The message stays "Disk utilization threshold reached 90% > 90%, stopping", which matches what @ikreymer said the behavior is. I'm using the Dockerfile in this repo using Docker CLI on Ubuntu LTS.

I was running an earlier version of zimit, and I just upgraded to the latest version. With the previous version the CPU metrics would get to 96% on a regular basis. I don't know why. It's the same machine and there's plenty of disk space and capacity on other non-CPU metrics as well. I picked 120 because I wanted a number there was no way it could reach. In other words, I picked a known invalid value on purpose. The default back to 90 makes complete sense. 

Thank you both very much! I will try using 0.
