### ISSUE TITLE
Astro Docs ZZZIIIMMM ! 🚀

### ISSUE THREAD

**Issue by bitsByB** [openzim/zimit#222]
Hi there, thank you for this very cool project!

- target website: https://astro.build/ 
- Youzim.it request number: 86204 succeeded
- Version: Linux desktop with Kiwix JS Electron 2.5.6

![image](https://github.com/openzim/zimit/assets/102392085/74335de7-9dfa-468c-863c-005d974726a5)

The result is almost perfect but:
- I can't only have the documentation section, I have to zim the whole site
- and THEN clicking the Documentation link opens a 2nd Kiwix window of the docs (which works pretty good)
How can I only Zim the documentation? (I tried but it doesn't work, getting the grayish color)

Cheers!

**Comment by benoit74** [comment]
The popup + the 2nd Kiwix window indicates that you did not ZIM the documentation at all. 
The term "external link" means a link to something which is external to the ZIM.
Your browsing of the docs works pretty well ... because it is the real docs website ^^
If you really only want to ZIM the doc, you should configure `https://docs.astro.build` as a target (instead of `https://astro.build`).

**Comment by bitsByB** [comment]
> Your browsing of the docs works pretty well ... because it is the real docs website ^^
@benoit74 no you didn't!! ah ah! silly me 😅

more seriously (besides now knowing Kiwix electron is almost pretty decent at browsing)
I did try unsuccessfully to Zim those (both files open on a black screen in Kiwix):
- https://docs.astro.build/
- https://docs.astro.build

each of those links when entered (in a real browser) redirect me to:
https://docs.astro.build/en/getting-started/
which I tried to Zim as well but I'm getting that grayed stuff where all links open external link

![image](https://github.com/openzim/zimit/assets/102392085/ed74601e-5974-4ea9-b3ef-f5543fc2c6a0)

Any idea on how to have this freaking documentation Zimed properly? (going into the woods soon)

**Comment by benoit74** [comment]
Oh, I'm sorry, I hopped it was just a configuration issue.
I will have a look into it with more attention later this week.
I will keep you updated.

**Comment by bitsByB** [comment]
Thanks a lot!

**Comment by benoit74** [comment]
Hello,
I had a look at job 0e9e5fe0, and the ZIM is working very well on kiwix-serve.
If I'm not mistaken, you are using Kiwix JS PWA, where support for ZIMs created by zimit is experimental and known to still have many issues.
I strongly encourage you to either use kiwix-desktop dor Windows (kiwix-serve is not the default in kiwix-desktop for Windows but available via the settings in the top-right corner) or kiwix-android. You might also use directly kiwix-serve if you are sufficiently technically skilled to start a server yourself (resources consumption is limited so it can run on a desktop machine but you will have to input commands in a terminal).

**Comment by benoit74** [comment]
More details about how to open ZIM files created by zimit has been posted [here](https://www.reddit.com/r/Kiwix/comments/170bnk1/how_to_open_zimit_files_eg_created_on_youzimit/).

**Comment by bitsByB** [comment]
ok thanks @benoit74,

I have few questions for you if you don't mind as I'd like to really understand how zim ecosystem works.
- I'm on linux mint and originaly I installed Kiwix desktop.
- All the zim file I download from the kiwix website works well with the desktop app
- when I want to open a file I created with youzim.it it doesn't work with the desktop app and I get:

![image](https://github.com/openzim/zimit/assets/102392085/d0fa930c-e770-4dfe-9deb-c98fde455065)

I see `Local Kiwix server` when I click the 3 dots in the upper right corner but using the local Kiwix server in the browser gives me an error:
![image](https://github.com/openzim/zimit/assets/102392085/c4c44c41-fb1d-45ba-bbe7-dc3f43e66cd0)
Are you saying I could have a better result by using kiwix-serve in Docker (I could do that)
- some of my zim files created with youzim.it work with Kiwix electron on Linux

- How/where are you able to check that job 0e9e5fe0? and you opened it
- did you check it in https://farm.openzim.org ?
- if so how? and if not what is it use for?

Thanks a lot Ben

**Comment by bitsByB** [comment]
@benoit74
https://www.reddit.com/r/Kiwix/comments/170bnk1/how_to_open_zimit_files_eg_created_on_youzimit/
great read, it answers some of my questions thanks a lot :)

**Comment by benoit74** [comment]
If you can use kiwix-serve, you should. Basically it is the "best" ZIM reader we have. It is the one behind  https://library.kiwix.org. And it is the one I used for my tests.

https://youzim.it is using a special farm at https://farm.youzim.it, this is where I found job 0e9e5fe0.

Since you found my very recent reddit post, I don't know if you still have questions. Basically, ZIM created with zimit are quite special since they use a service worker. ZIM file format does not pose any restriction on this kind of content, but it makes them much more difficult to read by most ZIM readers. Content of other ZIMs we produce with dedicated scrapers (i.e. not zimit) are more basic, simply a bunch of HTML / CSS / JS static files. We are progressively adopting more advanced JS frameworks inside the ZIM. Typically already done for freecodecamp.

**Comment by bitsByB** [comment]
Ok sounds great @benoit74 !
- I'm gonna install kiwix-serve and see what's up.
- ok cool for https://farm.youzim.it/ and finding older jobs (I found the devdocs.zim file on it but couldn't open it)
> Typically already done for freecodecamp.
What do you mean by that? freecodecamp is optimized for youzim.it?

**Comment by benoit74** [comment]
I meant that [freecodecamp scraper](github.com/openzim/freecodecamp) is already using a "modern" JS frontend (in Vue.JS).
