### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by SmallCoder13** [openzim/zimit#365]
I've been trying to install zimit all day. Would it be possible for some installation instructions to be posted to the README? It currently says how to use it, but not how to install it

**Comment by rgaudin** [comment]
@SmallCoder13 there is no such thing as installation for zimit. Zimit is meant to be used solely via [Docker](https://docs.docker.com/engine/install/). If you don't know how to use Docker, please check that first, there are plenty of tutorials online.
Then, you'll realize that there is no such thing as installation and you just run stuff off the docker image. That's why we only mention usage.

**Comment by SmallCoder13** [comment]
@rgaudin so the docker build command is the "installation" ?

**Comment by rgaudin** [comment]
The image is listed on the repo homepage sidebar (it's called a package in Github)

So basically you prepend the usage sample with 

```sh
docker run -it ghcr.io/openzim/zimit:dev
```

You need to mount a volume if you intend to access the resulting data as well. So here's a working example. Try it

```sh
docker run -v $(pwd)/output:/output -it ghcr.io/openzim/zimit:dev zimit --url https://perdu.com --name perdu.com_fr_all
```

This creates a ZIM file in the output folder of the current directory
