### ISSUE TITLE
Older version of zimit.kiwix.org worked better for fretmap.app

### ISSUE THREAD

**Issue by Rexadev** [openzim/zimit#372]
I made zim in 2024-03 and it worked perfectly but now https://s3.us-west-1.wasabisys.com/org-kiwix-zimit/other/fretmap.app_b8c984e0.zim I can't click the menu toggle and chord links aren't downloads
Old zim is 13.9MB and new is 8.6 Mb. Also Website has changed a little
Tested on Firefox Add-on and kiwix-desktop Windows 2.3.1

![image](https://github.com/user-attachments/assets/f44f9165-a6fd-4cf1-96fe-6261ed99ec50)

![image](https://github.com/user-attachments/assets/c414ee30-5ab3-4b80-81c8-d103f9a31972)

Chord Finder not working in New Zim
![image](https://github.com/user-attachments/assets/fb8bfc52-a368-4ac6-a194-72483d036050)

**Comment by benoit74** [comment]
I honestly doubt there is any link with zimit v2.

First because everytime you click a fret (or the menu button), there is a web request which is made. All those web requests are not "played/captured" by the crawler. And they hence cannot be replayed/simulated in offline mode in the ZIM.

Since you mention that website changed a little, I'm pretty sure it changed a lot from a technical point of view, and the new technology they are using is just not compatible with zimit.

Not something we can solve unfortunately, zimit is meant to be versatile but is not going to work with all websites.
