### ISSUE TITLE
[SPIKE] Consider reusing/patching 

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#4]
https://github.com/webrecorder/ proposes a quality set of tools to scrape random Web sites. We should decide if it would make sense to reuse/patch them for the Zimit project.

First of all the constraints:
* We need only the scraper part
* The scraper should work as a spider with arbitrary boundaries (only a subdomain or path structure for example)
* It should produce a ZIM
* The ZIM should be readable with Kiwix (without any change in Kiwix ideally)
* It should use new python-libzim binding
* Should use new organisation around namespaces, see https://github.com/openzim/libzim/issues/325.

I believe this raises a few questions:
* What would be the precise part of Webscraper project to reuse/hack?
* Could this write ZIM files?
* How do we deal with the problem that the whole tech stack seem to deal with the fact that HTTP headers need to be saved as well?
* Can we obtain a maintanable and robust product?

**Comment by kelson42** [comment]
@ikreymer Do you have a few thoughs about that?

**Comment by ivanistheone** [comment]
## Links

A while @tim-moody and  @ikreymer shared some links to WARC projects and I did some additional research about the WARC ecosystem and various tools and libraries and collected the following links, to the most promising projects. Sharing here in case this may be useful to you.

### Specs

 - ![](https://www.google.com/s2/favicons?domain=en.wikipedia.org) [Web ARChive - Wikipedia ](https://en.wikipedia.org/wiki/Web_ARChive)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)
 - ![](https://www.google.com/s2/favicons?domain=iipc.github.io) [The WARC Format ](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)
 
 
 ### Software libraries
 
 - ![](https://github.com/favicon.ico) [webrecorder/pywb ](https://github.com/webrecorder/pywb)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) Core Python Web Archiving Toolkit for replay and recording of web archives, and ![](https://www.google.com/s2/favicons?domain=pywb.readthedocs.io) [pywb docs](https://pywb.readthedocs.io/en/latest/index.html)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)

 - ![](https://github.com/favicon.ico) [webrecorder/browsertrix](https://github.com/webrecorder/browsertrix): High-Fidelity Browser-Based Automated Crawling + Behavior System

 - ![](https://github.com/favicon.ico) [webrecorder/warcit](https://github.com/webrecorder/warcit)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) Convert Directories, Files and ZIP Files to WARC. Like zimit.

 - ![](https://github.com/favicon.ico) [webrecorder/webrecorder-player) ](https://github.com/webrecorder/webrecorder-player)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) Webrecorder Player for Desktop (OSX/Windows/Linux). Like kiwix-serve.

 - ![](https://github.com/favicon.ico) [webrecorder/warcio: ](https://github.com/webrecorder/warcio)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) Streaming WARC/ARC library for fast web archive IO

 - ![](https://github.com/favicon.ico) [internetarchive/warcprox:  ](https://github.com/internetarchive/warcprox)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) WARC writing MITM HTTP/S proxy

 - ![](https://github.com/favicon.ico) [ArchiveTeam/grab-site](https://github.com/ArchiveTeam/grab-site)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) The archivist's web crawler: WARC output, dashboard for all crawls, dynamic ignore patterns 

 - ![](https://github.com/favicon.ico) [ArchiveTeam/wpull ](https://github.com/ArchiveTeam/wpull)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) Wget-compatible web downloader and crawler.

 - ![](https://github.com/favicon.ico) [machawk1/wail](https://github.com/machawk1/wail)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)  Web Archiving Integration Layer


### Python `warc` module

 - ![](https://www.google.com/s2/favicons?domain=warc.readthedocs.io) [warc: ](https://warc.readthedocs.io/en/latest/#reading-a-warc-file)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)  Python library to work with ARC and WARC files --- warc 0.1 documentation



### Crawlers

 - ![](https://github.com/favicon.ico) [cocrawler/cocrawler:](https://github.com/cocrawler/cocrawler)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) CoCrawler is a versatile web crawler built using modern tools and concurrency.

 - ![](https://github.com/favicon.ico) [internetarchive/brozzler: ](https://github.com/internetarchive/brozzler)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) distributed browser-based web crawler


### Archival apps
 - ![](https://www.google.com/s2/favicons?domain=webrecorder.io) [Webrecorder | Homepage ](https://webrecorder.io/)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)

 - ![](https://www.google.com/s2/favicons?domain=archivebox.io) [ArchiveBox](https://archivebox.io/)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)
 Uses several other archiveal services and also saves HTML, JS, PDFs, media, etc.
 
 - ![](https://www.google.com/s2/favicons?domain=perma.cc) [ Perma.cc = Indelible links ](https://perma.cc/)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png) and  ![](https://github.com/favicon.ico) [harvard-lil/perma:  ](https://github.com/harvard-lil/perma)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)

 - ![](https://github.com/favicon.ico) [webrecorder/webrecorder-desktop: Webrecorder Desktop App! ](https://github.com/webrecorder/webrecorder-desktop)

### Other collections of links

  - ![](https://github.com/favicon.ico) [iipc/awesome-web-archiving](https://github.com/iipc/awesome-web-archiving#tools--software)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png):
  List for getting started with web archiving 

  - ![](https://www.google.com/s2/favicons?domain=www.archiveteam.org) [The WARC Ecosystem - Archiveteam ](https://www.archiveteam.org/index.php?title=The_WARC_Ecosystem#WARC_viewer)![](chrome-extension://chphlpgkkbolifaimnlloiipkdnihall/images/cross.png)


## Findings

It seems the WARC ecosystem is not suitable for the purpose of adapting web content for offline use (scraping), since it works at too low level. Basically a WARC file is something like a HTTP proxy that you can "save" and replay later, which makes it very powerful but also very heavyweight.

The `pywb` project is capable of recording WARC files, but its focus seems different from what we (Kiwix, IIAB, BSF, WP, LE) need — it records all HTTP traffic and doesn't try to extract the actual html and assets. Also, @ikreymer will correct me if I'm wrong, I didn't see any crawling logic --- `pywb` provides just the recording part and not the crawling (there needs to be another script/tool to visit all the pages on the website and feed the page URLs to `pywb` do the recoding part).

The `wpull` command seems very promising but it doesn't support pages rendered using JavaScript.  There is ["experimental" support for dynamic pages](https://wpull.readthedocs.io/en/master/usage.html#phantomjs-integration), but I tried it and got nothing but errors during install and in the end it didn't work.

The two most promising projects for a js-capable solution are `browsertrix` and `brozzler + warcprox`, which are based on a real browser + capable of doing recursive crawling. I recorded short video demo of what running brozzler looks like: https://www.youtube.com/watch?v=NQVGUdvAbf0 trying to scrape the learnignequality.org site. It did good job at visiting all the page in a fully automated manner, so it might be looking into it.

One problem was the result of the crawl+scrape+archive steps were around 2G of WARC files. I don't know what could possibly take up so much space. Maybe it found the .deb and .exe installers for old Koibri versions? Even then 2G seems like a lot. 


## Summary

The WARC ecosystem has tools "deep scrape" any website and create a local copy. In order to obtain actual HTML pages (.html) and assets (.png/.js/.css/etc) required to produce (zim files, RACHEL modules, Kolibri channels, etc.) would require additional "extraction" steps but these steps would be much faster and reproducible since we would be scraping content from a local WARC archive.

Unfortunately I haven't had time to look into WARC format much after these initial tests. At LE we've tried various approaches for crawling[[1](https://github.com/learningequality/BasicCrawler#basiccrawler),[2](https://github.com/learningequality/BasicCrawler/blob/master/chefdata/trees/learningequality_web_resource_tree.json)], scraping[[3](https://github.com/learningequality/webmixer#page-scrapers)], and archiving[[4](https://github.com/kollivier/ricecooker/blob/5b63531642ae579d17c1b77602948ec95772ada7/ricecooker/utils/downloader.py#L280-L356)], but all of these are in an experimental/alpha phase and not ready for prime time yet.

I'll keep you posted if we one of these tools develop into a general-purpose scraping solution that might be useful for you as well. Please keep us (myself and my colleague @kollivier) posted too on any research findings or tools you develop around WARCs in case we could learn from them and collaborate on scraping efforts.

**Comment by ikreymer** [comment]
Apologies for late response! I've been meaning to weigh in earlier, but was just swamped with other things.
Thanks for this thorough analysis. Yes, pywb includes recording and replay capabilities, but is not itself a crawler, for that, we have Browsertrix which uses pywb under the hood and automates the process. Browsertrix is built using Docker and I'm currently refactoring it to run on Kubernetes to be able to scale better. Brozzler is a similar solution from Internet Archive.
You'll probably want to use one of these tools to run the crawl.

Most existing crawling solutions will create WARC files, and for good reason.

> It seems the WARC ecosystem is not suitable for the purpose of adapting web content for offline use (scraping), since it works at too low level. Basically a WARC file is something like a HTTP proxy that you can "save" and replay later, which makes it very powerful but also very heavyweight.

I would strongly disagree with this conclusion, however. The 'offline use' and the 'web archiving replay' use case are essentially the same! The goal is to be able to replay archived pages in a different environment, without being connected to the live site -- it can be offline, it can be hosted on another platform, that doesn't make a difference.

The WARC format, despite its limitations, is very simple to use. It is basically a record of the HTTP traffic with additional metadata added in front. Each record is gzipped to allow random access. The main limitation of WARCs is that they do not include a built-in index, which is usually built and maintained separately. I think that's one advantage of the zim format.

> The WARC ecosystem has tools "deep scrape" any website and create a local copy. In order to obtain actual HTML pages (.html) and assets (.png/.js/.css/etc) required to produce (zim files, RACHEL modules, Kolibri channels, etc.) would require additional "extraction" steps but these steps would be much faster and reproducible since we would be scraping content from a local WARC archive.

We have tools to extract the content from WARC, the `warcio` library already has such a command.

However, I want to emphasize that all of this is not the 'hard part', when it comes to dynamic, complex pages. It's easy to extract html/image/js/css from WARCs. But the reason for archiving and replaying HTTP traffic is that you *don't know* ahead of time what will be needed to make dynamic, complex pages work! For example, there might be a tiny, <1K json or custom query response that is required for a dynamic, JS based site to work. The file is negligible in storage size, but makes all the difference between a working site and a blank page with errors. I've seen this many times.
When it comes to dynamic pages, you often don't know what is needed until you attempt to play it back. And sometimes there may be different assets for different resolutions/browsers/etc.. so it's not always easy to tell by a single replay attempt either.

I'm not entirely clear what the constraints are, and I'd be concerned about building an entirely new system and 'reinventing the wheel' as far as crawling and/or replay, as it sounds like the problems you're facing are the same as the web archiving field has been working to solve for years as well.

If the main concern is storage space + format, it should be possible to convert WARC files to zim. pywb could probably even be expanded to write/read zim files directly. It seems like main limitation of ZIM is that it's not possible to store the HTTP headers. 
The HTTP headers are of course small compared to the content, though it may have an impact on replayability of certain sites. It's hard to tell ahead of time, and is dependent on the site. (For example, if a site requires a certain cookie, or custom header loaded via ajax, they may be needed, otherwise probably ok).

Probably a better option then is to create a warc2zim utility that has a number of options, and can be run with different parameters to convert WARC files to ZIM. That would be my recommended approach, as different options can be tried this way.

In my opinion, the harder part is not the capture, but the replay, because sometimes you 'don't know what you don't know' in terms of what is needed to replay a complex, dynamic page accurately.

Happy to answer any more questions!

**Comment by ivanistheone** [comment]
>> It seems the WARC ecosystem is not suitable for the purpose of adapting web content for offline use (scraping), since it works at too low level.

> I would strongly disagree with this conclusion, however. The 'offline use' and the 'web archiving replay' use case are essentially the same!

I think I disagree with my own conclusion too ;)  I think what I was trying to say is that WARC *alone* is not suitable for the bundling for offline use, for the following two reasons:
  - using WARC files also requires a WARC-player component to be implemented in the various apps to play back the WARC files, which might not be possible (e.g. the Kolibri HTML player assumes all html content and assets are just files on local path with relative paths, the same way you could load a static website as file:// ).
 - the goal of WARC is faithful reproduction of the website content (i.e. archival) while the offline learning use case sometimes requires transforming the content (e.g. to restructure, select, or modify parts of the content) as a post processing step, which would be done easier with the files extracted. For example, we commonly use ffmpeg to compress videos to make them smaller.

That being said I think WARC + all the tools in the ecosystem could be an important step to making all our work of archiving educational websites much more robust, reliable, and performant. Here is a four-step pipeline that could work:
```
website --> (1) archiving --> (2) extract --> (3) transform[?] --> (4) packaging[*] --> offline use
```
where step (1) is based around WARC files, step (2) is a website-specific extraction step that could be shared between orgs, step (3) can perform optional transformations (e.g. video compression), and step consists (4) are different set of packaging scripts for different platforms (zim files, RACHEL modules, Kolibri channels, etc.).

If tools from the WARC ecosystem can help us with step (1) and (2), then half the battle is already won!


> We have tools to extract the content from WARC, the warcio library already has such a command.

Could you provide some links or info or code about this. I'm particularly interested in something like a "manifest" that lists all the files/resources that were downloaded.


> you don't know ahead of time what will be needed to make dynamic, complex pages work! 

I hear you. A generic scraper and extractor that works on ALL pages is a very hard task. This is why I'm working with the human-in-the-loop assumption, either a developer who is offline-ing the content or the educator that requested the content offline can check the offline-ing processed has worked.

**Comment by ikreymer** [comment]
> > I would strongly disagree with this conclusion, however. The 'offline use' and the 'web archiving replay' use case are essentially the same!
> 
> I think I disagree with my own conclusion too ;) What I was trying to say is that WARC _alone_ is not suitable for the bundling for offline use, for the following two reasons:

Ok, that is more fair! I would agree with that as well, namely because WARC format lacks a built in index or a way to store standardized metadata about what the pages are in the WARC.

> 
> * using WARC files also requires a WARC-player component to be implemented in the various apps to play back the WARC files, which might not be possible (e.g. the Kolibri HTML player assumes all html content and assets are just files on local path with relative paths, the same way you could load a static website as file:// ).

This has been true, but is beginning to change, and has been a major focus of my some of my work recently. It should be possible to replay WARC files directly in the browser, especially using service workers. This allows for web archives to be hosted using static file storage.
(See this blog post: https://blog.webrecorder.io/2019/10/03/client-side-replay.html)
(An example which replays via service workers: https://wab.ac/?coll_example=examples/netpreserve-twitter.warc&url=/example/https://twitter.com/netpreserve)
This renders a dynamic twitter site from a static hosted WARC file on github pages (https://github.com/ikreymer/wabac.js/blob/master/examples/netpreserve-twitter.warc)

Of course, this approach is not at all tied to the storage format, and would be great to support with other formats.

> * the goal of WARC is faithful reproduction of the website content (i.e. archival) while the offline learning use case sometimes requires transforming the content (e.g. to restructure, select, or modify parts of the content) as a post processing step, which would be done easier with the files extracted. For example, we commonly use ffmpeg to compress videos to make them smaller.

The WARC format just stores the content. The reproduction/replay is done via the player/replay system, and the requirements are similar than you may think.
For example, here's [an experimental workflow that I've added to the `warcit` tool to convert
flash video into other formats, using ffmpeg](https://github.com/webrecorder/warcit/wiki/Warcit-Video-Audio-Conversion) The reason? Flash video doesn't really work anymore, so its necessary to convert it to make it usable, and videos captured separately also don't automatically replay, so some type of post-processing conversion is necessary. The WARC format has a record called 'conversion' that is actually designed for this type of derivative, though it hasn't often been used.

The main difference seems to me that you are more constrained with storage, and therefore have to choose what to store to make available in limited storage scenarios, unlike institutions that can afford to store everything they crawl.

> 
> That being said I think WARC + all the tools in the ecosystem could be an important step to making all our work of archiving educational websites much more robust, reliable, and performant. Here is a four-step pipeline that could work:
> 
> ```
> website --> (1) archiving --> (2) extract --> (3) transform[?] --> (4) packaging[*] --> offline use
> ```
> 
> where step (1) is based around WARC files, step (2) is a website-specific extraction step that could be shared between orgs, step (3) can perform optional transformations (e.g. video compression), and step consists (4) are different set of packaging scripts for different platforms (zim files, RACHEL modules, Kolibri channels, etc.).

Yes, I think the workflow makes sense. I'm not as familiar with this ecosystem, so don't know what all of these provide. I think a lot of the complexity is still in the replay, if a site requires more than a static file, but to respond to dynamically changing http requests.
The service worker approach I am working on is designed to be able to handle such a site while loading static files from a backend storage, happy to share more details about that if it would be helpful.

> 
> If tools from the WARC ecosystem can help us with step (1) and (2), then half the battle is already won!
> 
> > We have tools to extract the content from WARC, the warcio library already has such a command.
> 
> Could you provide some links or info or code about this. I'm particularly interested in something like a "manifest" that lists all the files/resources that were downloaded.
> 
The warcio index command will give you a manifest as line-delimited json, with options for various fields:
https://github.com/webrecorder/warcio#index

The extract command can extract the payload/content from the WARC:
https://github.com/webrecorder/warcio#extract

These are command-line but should be mostly straightforward to integrate into a python library workflow.

> > you don't know ahead of time what will be needed to make dynamic, complex pages work!
> 
> I hear you. A generic scraper and extractor that works on ALL pages is a very hard task. 

Yes, agreed. It's what I have been trying to do for last few years, i can confirm its a hard problem :)

> For the above pipeline, I'm working under a human-in-the-loop assumption (either a developer or an educator) who can verify that steps (2), (3), and (4) have worked correctly, on a case-by-case basis.
Yes, some verification by humans will likely always be necessary, but probably needs to be made as simple as possible. It might not be realistic to have a human verify hundreds or thousands of pages, for example.

What is the general size/scope of the sites you're dealing with? Is there a certain size limit that you need to stay under for offline use?

**Comment by kelson42** [comment]
@ivanistheone Nice to see you participating to this discussion, I was so busy at the time you made the comment that it took me two months to answer. So first of all thank you very much for sharing the list of tools we could reuse here, we were at this really level of the conception stage. We had found many of them on our own and @pirate shared with us an even more complete list.

As a side note I was quite suprised you have been working with @tim-moody on an other one crawler at https://github.com/learningequality/BasicCrawler. We still don't have made decision on the spider side, but to the contrary of what you have done, we would really like to take/improve an existing one.

I was happy as well to read your small exchange with @ikreymer about the warc/zim comparisons which is interesting and for which I share many of the thoughs you both had.

I'm just about to close this ticket as we made a few steps forward in the reflexion and have taken a few decisions concerning what we want to do in the near future. We will work with @ikreymer and create a derivated version of WebRecorder's webplayer.js able to be embedded in a ZIM file and read content from the ZIM itself. The usage of it will be by converting WARC files to ZIM via [warc2zim](https://github.com/openzim/warc2zim). A version 1.0 will be ready in August.

The question of which Spider to use for Zimit is quite open but tracked in ticket #5.
