### ISSUE TITLE
Disk utilization threshold reached 90%

### ISSUE THREAD

**Issue by hamoudak** [openzim/zimit#426]
am having issues with this message"Disk utilization threshold reached 90%". this is the first time to go with zimit image on docker; I can't make a complete crawl for any website. I have deleted my containers and deleted the directory folders of my crawls to start over the process. thinking may be something related to overwrites. I have no experience, could you help me on this?  before this I got " rolloversize exceeded the limit". also when I launch a command I get "docker: error during connect: Post "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/containers/create?" but I restart docker and the command works normally.

![Image](https://github.com/user-attachments/assets/706c3978-23a4-4988-bc36-2958dc0e528d)

![Image](https://github.com/user-attachments/assets/c98a11d7-e7f4-46c0-8a30-fd464e4fddf1)

**Comment by vitaly-zdanevich** [comment]
I believe that the software should check not the percentage but stop if less than 100 MB available.

**Comment by vitaly-zdanevich** [comment]
@hamoudak search in the repo before creating a new issue https://github.com/openzim/zimit/issues/394

Solution: `--diskUtilization 0`

**Comment by benoit74** [comment]
Currently the crawler (and not the whole scraper) is checking for disk space usage in percentage. By default, if disk usage is above 90%, the software will stop immediately. Everything is hence normal here. If you are OK with using more than 90%, you can adjust the threshold with `--diskUtilization xx`. Or completely disable the check with `--diskUtilization 0`. 

Regarding `rolloversize exceeded the limit` message, these are normal messages indicating that the crawler has finished filling one WARC file (the intermediate archives created by the crawler) and is creating a new one. Do not be worried by these messages.

Regarding `docker: error during connect: Post "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.47/containers/create?` message, this looks like something related to your local setup of Docker, not something we can really help with unfortunately.

@vitaly-zdanevich Current default is probably meant to be a conservative default setting so that we do not have users complaining our software bricked their machine by using all space available. But indeed on some machines an absolute value would help much more than a percentage. Do not hesitate to open an issue at https://github.com/webrecorder/browsertrix-crawler to discuss this (this check is done in the crawler, not the scraper).

**Comment by hamoudak** [comment]
thank you so much, you have made it very clear to me.
