### ISSUE TITLE
Links only display page upon refresh

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#47]
This behaviour is seen on edu.gcfglobal.org : when I click on any link the pages appear blank. If I hit "refresh" then the page appears normally.

**Comment by kelson42** [comment]
This is probably the last challenging problem we have regarding the V1.0 of Zimit. Any idea what is going on?

**Comment by ikreymer** [comment]
Can you confirm that this is happening only in Chrome?

I have seen this happen with other sites as well, and think its a Chrome issue, perhaps this: https://bugs.chromium.org/p/chromium/issues/detail?id=1142725#c33

The page reappears not just after refresh, but after resizing the window, or even inspecting it in DevTools -- it just doesn't render after initial load.

It appears to be fixed in the latest Chrome Canary as I wasn't able to repro it there.

Can you test with other browsers and Chrome Canary to confirm if you're seeing the same issue?

**Comment by ikreymer** [comment]
After more testing, it seems that it is fixed in Chrome Dev/Canary (Chrome 88+), but not in 86 or 87.

I made a comment there with consistent repro: https://bugs.chromium.org/p/chromium/issues/detail?id=1142725#c63

**Comment by kelson42** [comment]
@Popolechien @rgaudin We will needyour eedback here to confirm the browser/version specific bug, so nothing to fix on our side.

**Comment by rgaudin** [comment]
Works for me

**Comment by ikreymer** [comment]
Chromium devs think its actually a separate bug, can follow along here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1149059
