### ISSUE TITLE
Most of the pictures missing in wiki.openzim.org

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#63]
Capturing https://wiki.openzim.org/ with youzim.it works, but most of the pictures don't display properly:
![image](https://user-images.githubusercontent.com/1029718/101900083-2d48e680-3baf-11eb-8e13-31b333b04e1c.png)

**Comment by kelson42** [comment]
Here is the file: 
[wiki.openzim.org_en_all_2020-12.zim.zip](https://github.com/openzim/zimit/files/5678956/wiki.openzim.org_en_all_2020-12.zim.zip)

**Comment by rgaudin** [comment]
[The task](https://farm.youzim.it/pipeline/9b42f21960ce95f803a53df5/debug) had a 100 limit and that number was hit so I would advise to check by running the container without the limit before investigating further.

**Comment by Popolechien** [comment]
FWIW I have the same issue of missing images on a Wordpress website : banner is ok whereas images within posts are not there
![Screenshot_20201211_145642](https://user-images.githubusercontent.com/21675885/101912065-8b7ec500-3bc1-11eb-9bc3-260bf101c93c.jpg)
)

**Comment by Popolechien** [comment]
Tried again with limit at 1000 and zimming 189 pages - still no images.

**Comment by kelson42** [comment]
This problem starts to worry me a bit.

**Comment by rgaudin** [comment]
@Popolechien what did you restart ? openzim or the other one ? Can you share the task id or link ?

**Comment by Popolechien** [comment]
Task 4484f. Odd thing is, it seems to keep downloading the same file from 2 days ago: success message indicates I should get a 68 Mb file but I just noticed I always get the same 15.9 Mb one.

**Comment by rgaudin** [comment]
Good catch! indeed file can't overwrite on the bucket so it's ils file.
We have fixed that by using unique file names but it's not deployed yet.
zimfarm doesn't consider upload status for overall task status. maybe we should revise that...

**Comment by kelson42** [comment]
@rgaudin Yes, somehowit will have if we want to integrate the quaratine process properly I guess

**Comment by ikreymer** [comment]
I can try running this crawl locally, the images should captures if the page is loading..

**Comment by ikreymer** [comment]
I think I found the issue which is two-fold:
1) the image is using an `<img srcset>` tag, and the crawler does not yet have 'auto fetching' of srcsets, but I do have a script that does this.
2) The replay sets `window.devicePixelRatio` to 1, which is why the replay it uses a different version of srcset in this case than when browsing, but it does not set it when crawling, which is why you see this even on desktop. I am not sure if devicePixelRation should be adjusted at all, or maybe should always use the same version on crawling and replay. I've wanted to check if this affect other things as well.

I'll add a fix for 1) in browsertrix-crawler that should grab all of the srcset versions, which I think should fix this!
