### ISSUE TITLE
ZIMing a portion of a website?

### ISSUE THREAD

**Issue by W1LMS** [openzim/zimit#94]
Hello,

I attempted to ZIM the prehospital care manual to store in an event of an emergency/disaster. I am part of the volunteer team that handles communications and resources during such an event. The site is located at: https://dhs.lacounty.gov/emergency-medical-services-agency/home/resources-ems/prehospital-care-manual/

Is it possible to ZIM this site? I attempted to with youzim.it (task 74478), but it failed.

Thanks for your help!

**Comment by kelson42** [comment]
@W1LMS It shoudl work, we will anlyze why it does not.

**Comment by kelson42** [comment]
@W1LMS The problem here is that the TLS/HTTPS of the upstream Web site is wrongly configured. See https://www.ssllabs.com/ssltest/analyze.html?d=dhs.lacounty.gov&s=45.60.151.78&latest. It is not delivering the intermediate CA certificate and therefore the trust chain can not be verified by the browser/scraper. You can write the Webadmin and ask him to fix the problem.

**Comment by W1LMS** [comment]
Thank you!
