### ISSUE TITLE
h2g2.com ZIM doesn't load

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#95]
Task https://youzim.it/d94782231a21a4c3fb2ab806 apparently succeeded in scraping https://www.h2g2.com and yielded an 85Mb file. However said file refuses to open on android. No error message, it simply shows an empty screen with a continuously rolling circle.

I don't know how (un)related this is, but the webview confirmation/monitoring page had an error message appearing at some point during the process. 
![Capture d’écran 2021-04-30 à 11 44 32](https://user-images.githubusercontent.com/21675885/116678340-7c01ec00-a9a9-11eb-81a6-97c6b22a5a60.png)

**Comment by rgaudin** [comment]
Completely unrelated.

**Comment by kelson42** [comment]
@rgaudin This ticket is, at least in the wrong repository right? Not sure either there is anything concretly we could beside answering properly to the legit question of @Popolechien?!

**Comment by rgaudin** [comment]
Which one is the legit one? The error message? Means some request to an API failed. Was about a year ago, nothing to add :/

**Comment by kelson42** [comment]
@Popolechien If a ZIM file is not able to open with Kiwix, then a ticket should be open in the appropriate Kiwix repository. If you do so, it is important to provide all the usual details and ideally the ZIM file itself (or a link to download it).

The screenshot you have furnished reports an API error or lack of response. Considering that this ticket is super old and that we have migrated our whole infrastructure in the meantime, there is nothing we can do anymore on that. Actually, I'm not even sure I have see once this kind of API error since we have migrated to K8s. Might be solved. If not, please reopen a new ticket.

Sorry for this late and not so usefuly feedback. I have created https://farm.openzim.org/recipes/h2g2.com in an attempt to reproduce the bug.
