### ISSUE TITLE
Is it possible to limit crawler to single subreddit?

### ISSUE THREAD

**Issue by kodxana** [openzim/zimit#96]
Can we set crawler to crawl only specified subreddit without starting to crawl whole reddit :)

**Comment by kelson42** [comment]
Should be, have you tried?

**Comment by kodxana** [comment]
Testing right now. Also is it possible to use zimit-gui with local instance rather than public server?

**Comment by rgaudin** [comment]
The UI, hardly as the UI communicates with a zimfarm instance which itself communicates with a worker that actually runs the task.
But you can surely replicate it all if you're willing to. Check repos: zimit-frontend and zimfarm in this org.

I'd advise you use Zimit docker container so that you'd be free of the public server limit. Command-line only though.

**Comment by kodxana** [comment]
I noticed that docker not saves zim file when I was using it.
```
docker run  -v /media/box2/out:/output --cap-add=SYS_ADMIN --cap-add=NET_ADMIN \
       --shm-size=1gb openzim/zimit zimit --url http://kodlyoko.hpu.pl --name kodlyoko.hpu.pl --workers 8 --waitUntil domcontentloaded --output /output

**Comment by rgaudin** [comment]
Looks good. If it didn't produce a ZIM file, please open another ticket sharing the command used and its output.

**Comment by kodxana** [comment]
About reddit it looks like it grabs all reddit links mentioned in subreddit not just selected subreddits links.

**Comment by rgaudin** [comment]
See scope option.
